package EnumsForAutos;

public enum OpelModels {

    ADAM,AGILIA,ROCKS,AMPERA,
    ANTARA,ASTRA,CASCADA,COMBO,
    CORSA,INSIGNIA,KARL,MAREVIA,
    MOKKA,MOVANO,SIGNUM,TIGRA,
    VECTRA,VIVARO,ZAFIRA
}
